name: Sync LeetCode Solutions

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync_leetcode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync LeetCode Solutions
        uses: YvanCC/leetcode-sync-action@main
        with:
          github_token: ${{ secrets.LEETCODE_TOKEN }}
          leetcode_username: "ikramchafai"
          leetcode_password: ${{ secrets.LEETCODE_PASSWORD }}
          repo_name: "ikramch23/LeetCode-GitHub-Integration"

   
